// Usage: bun scripts/emoji-table.ts
// Writes src/core/emoji/emojiTable.ts, and the web app's copy in web/src/slack: every
// emoji with the short names Slack knows it by, from iamcal/emoji-data (the data set
// Slack itself uses). Run it again to pick up a newer version; nothing else needs to change.
import { join } from 'node:path';

const VERSION = 'v16.0.0';
const SOURCE = `https://raw.githubusercontent.com/iamcal/emoji-data/${VERSION}/emoji.json`;
const PER_LINE = 12;

interface Entry {
  readonly unified: string;
  readonly short_names: readonly string[];
  readonly sort_order: number;
}

const response = await fetch(SOURCE);

if (!response.ok) {
  throw new Error(`${SOURCE}: HTTP ${response.status}`);
}

const entries = ((await response.json()) as Entry[])
  .sort((a, b) => a.sort_order - b.sort_order)
  .map(
    (entry) =>
      `${String.fromCodePoint(...entry.unified.split('-').map((hex) => parseInt(hex, 16)))}:${entry.short_names.join(',')}`
  );
const lines = Array.from({ length: Math.ceil(entries.length / PER_LINE) }, (_, index) =>
  entries.slice(index * PER_LINE, (index + 1) * PER_LINE).join('|')
);

const table = (note: string) =>
  `// Generated by scripts/emoji-table.ts from iamcal/emoji-data ${VERSION}; do not edit.
${note}// Each entry is \`emoji:short_name,alias…\` — the names Slack uses for reactions.
export const EMOJI_TABLE = \`
${lines.join('\n')}
\`;
`;

await Bun.write(join(import.meta.dir, '../src/core/emoji/emojiTable.ts'), table(''));
await Bun.write(
  join(import.meta.dir, '../web/src/slack/emojiTable.ts'),
  table("// The web app's copy of src/core/emoji/emojiTable.ts (web/ only talks to the API).\n")
);

console.log(`${entries.length} emoji written`);
